server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  cloud:
    config:
      discovery:
        enabled: true
        uri: http://localhost:9296
  zipkin:
    base-url: http://localhost:9411/
