server:
  port: 9296

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanatho/config-server-code-buffer
          clone-on-start: true
          default-label: main